# Generated by Django 4.1.2 on 2022-10-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
