# Generated by Django 4.1.2 on 2022-10-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0002_task_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
